name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Flutter App
        run: |
          # Create a new flutter app inside the current directory
          flutter config --no-analytics
          flutter config --no-analytics
          flutter create mobile_app --platforms android
          cd mobile_app
          
          # Add webview package
          flutter pub add webview_flutter

          # Copy main.dart from the repo
          cp $GITHUB_WORKSPACE/android_main.dart lib/main.dart

          # Change App Name to KabuTech
          sed -i 's/android:label=".*"/android:label="KabuTech"/g' android/app/src/main/AndroidManifest.xml

          # Set App Icon using flutter_launcher_icons
          flutter pub add --dev flutter_launcher_icons
          echo "flutter_launcher_icons:" > flutter_launcher_icons.yaml
          echo "  android: true" >> flutter_launcher_icons.yaml
          echo "  image_path: \"$GITHUB_WORKSPACE/public/assets/logo.png\"" >> flutter_launcher_icons.yaml
          dart run flutter_launcher_icons

          # Add internet permission for Android
          sed -i 's/<application/<uses-permission android:name="android.permission.INTERNET" \/>\n    <application/' android/app/src/main/AndroidManifest.xml

          # Build APK
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kabutech-hiyas-apk
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
